fieldLayouts:
  fbddc104-cf13-4ba6-8293-35f8166aecca:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: d20136ac-1e31-4c44-a588-8b385f2627f0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e4a284e3-2244-492e-89de-7fcbb7e392d8
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f223541d-0057-4b42-8f60-11587c05dbf9
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Main
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 13c6850e-3517-47ef-87e2-e01f728a06d5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3fd6881a-8adc-40ad-990a-ae8344de3362
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: aff46670-72d3-4242-baa5-ce06a7dc3952
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Meta
        sortOrder: 2
handle: homepage
hasTitleField: false
name: Home
section: 11ec7483-818b-469e-b562-2732cba299e7
sortOrder: 1
titleFormat: '{section.name|raw}'
