fieldLayouts:
  2b810ebc-24b9-4e73-b623-78f1b1f96b81:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: e4a284e3-2244-492e-89de-7fcbb7e392d8
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e8013185-75cb-4cc3-83df-74bc8f4c3a64
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Main
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 13c6850e-3517-47ef-87e2-e01f728a06d5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3fd6881a-8adc-40ad-990a-ae8344de3362
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: aff46670-72d3-4242-baa5-ce06a7dc3952
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Meta
        sortOrder: 2
handle: section404
hasTitleField: false
name: '404'
section: 7ad2df02-6aae-43ce-8d18-4ec63e98394f
sortOrder: 1
titleFormat: '{section.name|raw}'
