childBlocks:
  - text
  - socialVideo
  - image
  - imageText
  - textWithBackground
field: f223541d-0057-4b42-8f60-11587c05dbf9
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: c226c532-086f-410f-a5d2-32e0854771bd
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a9b1fe21-6b14-4f6d-aeb5-76c232e8a7a3
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5a72de37-5a52-4c64-ac04-16d19fd02ef2
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 32f312f9-f788-46e9-a60e-9dea685ededb
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8f50e70e-171a-413d-9675-189a61c3b153
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d9869f7-7677-4cb3-b142-3660d90d576c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dc80296e-6637-45d8-9b63-1eb7ecb8b0e1
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0de45245-1f4e-40bb-a6ee-5bd3bf466701
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: db03ff3a-df92-453f-9e20-35bc8667d83d
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 31a78a9a-2ab7-414a-bc5e-bbf21b31092d
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 174dbb59-9ec4-41d8-bb34-4ff50a88c694
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 78733c9a-3026-48a3-9a2e-c1f5d3ffd2d8
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bcd95e58-4270-455a-ac1a-a2f34bc6806c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: carousel
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Carousel
sortOrder: 1
topLevel: true
