childBlocks:
  - text
  - socialVideo
  - image
  - imageText
  - textWithBackground
field: f223541d-0057-4b42-8f60-11587c05dbf9
fieldLayouts:
  f017f72c-cdd5-43e0-a8cf-cc5a320ee389:
    tabs:
      -
        fields:
          0d9869f7-7677-4cb3-b142-3660d90d576c:
            required: false
            sortOrder: 6
          0de45245-1f4e-40bb-a6ee-5bd3bf466701:
            required: false
            sortOrder: 8
          174dbb59-9ec4-41d8-bb34-4ff50a88c694:
            required: false
            sortOrder: 11
          31a78a9a-2ab7-414a-bc5e-bbf21b31092d:
            required: false
            sortOrder: 10
          32f312f9-f788-46e9-a60e-9dea685ededb:
            required: false
            sortOrder: 4
          5a72de37-5a52-4c64-ac04-16d19fd02ef2:
            required: false
            sortOrder: 3
          78733c9a-3026-48a3-9a2e-c1f5d3ffd2d8:
            required: false
            sortOrder: 12
          8f50e70e-171a-413d-9675-189a61c3b153:
            required: false
            sortOrder: 5
          a9b1fe21-6b14-4f6d-aeb5-76c232e8a7a3:
            required: false
            sortOrder: 2
          bcd95e58-4270-455a-ac1a-a2f34bc6806c:
            required: false
            sortOrder: 13
          c226c532-086f-410f-a5d2-32e0854771bd:
            required: false
            sortOrder: 1
          db03ff3a-df92-453f-9e20-35bc8667d83d:
            required: false
            sortOrder: 9
          dc80296e-6637-45d8-9b63-1eb7ecb8b0e1:
            required: false
            sortOrder: 7
        name: Settings
        sortOrder: 1
handle: carousel
maxBlocks: 0
maxChildBlocks: 0
name: Carousel
sortOrder: 1
topLevel: true
