childBlocks: ''
field: f223541d-0057-4b42-8f60-11587c05dbf9
fieldLayouts:
  fbb33f09-529f-4b89-aa1a-937c8f40b4ee:
    tabs:
      -
        fields:
          45ea03a3-c41e-4ab3-bccf-2ea2d9c1e21e:
            required: false
            sortOrder: 5
          93e318a1-9a35-4cf7-b3e8-582916bfb7ef:
            required: false
            sortOrder: 1
          93f66945-268c-495f-bd44-4e4f8343a4f9:
            required: false
            sortOrder: 2
          da0152ae-2c5c-4580-90c9-19a135efd32e:
            required: false
            sortOrder: 4
          e8013185-75cb-4cc3-83df-74bc8f4c3a64:
            required: false
            sortOrder: 3
        name: Main
        sortOrder: 1
handle: imageText
maxBlocks: 0
maxChildBlocks: 0
name: 'Image Text'
sortOrder: 8
topLevel: false
