childBlocks: ''
field: f223541d-0057-4b42-8f60-11587c05dbf9
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: 93e318a1-9a35-4cf7-b3e8-582916bfb7ef
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 93f66945-268c-495f-bd44-4e4f8343a4f9
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8013185-75cb-4cc3-83df-74bc8f4c3a64
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: da0152ae-2c5c-4580-90c9-19a135efd32e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 45ea03a3-c41e-4ab3-bccf-2ea2d9c1e21e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
handle: imageText
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Image Text'
sortOrder: 9
topLevel: false
