contentColumnType: text
fieldGroup: d89526f0-270b-4f39-8afb-812fe0300304
handle: cookieBannerReadMoreLabel
instructions: ''
name: 'Cookie Banner Read More Label'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'Read More'
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
