contentColumnType: text
fieldGroup: a61e403f-3fd4-4ce8-9513-5dce27201307
handle: externalLink
instructions: ''
name: externalLink
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'https://google.com'
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
