contentColumnType: text
fieldGroup: 8d3aee83-3990-4b7e-984c-a93af1a5d317
handle: googleMapsApiKey
instructions: 'API-Key from the Google Maps Javascript API. Credit Card needs to be setup. More information: https://developers.google.com/maps/documentation/javascript/get-api-key'
name: 'Google Maps API Key'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
