contentColumnType: text
fieldGroup: 8d3aee83-3990-4b7e-984c-a93af1a5d317
handle: googleMapsCookieMsgSpecific
instructions: 'Detailed description why Google Maps needs Cookies.'
name: 'Cookie Message Specific'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Google Maps needs Cookies to work.'
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
