contentColumnType: text
fieldGroup: 8d3aee83-3990-4b7e-984c-a93af1a5d317
handle: googleMapsLong
instructions: 'Longitute of the coordinate on Google Maps.'
name: 'Google Maps Long'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
