contentColumnType: boolean
fieldGroup: d1f3b0d0-bb53-4580-b535-3574ed35136f
handle: isInfinite
instructions: ''
name: 'Is Infinite'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
