contentColumnType: string
fieldGroup: d1f3b0d0-bb53-4580-b535-3574ed35136f
handle: orientation
instructions: ''
name: Orientation
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Horizontal
        -
          - value
          - horizontal
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Vertical
        -
          - value
          - vertical
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
