contentColumnType: boolean
fieldGroup: a61e403f-3fd4-4ce8-9513-5dce27201307
handle: showTitle
instructions: ''
name: 'Show Title'
searchable: false
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
