enableVersioning: true
handle: homepage
name: Home
propagationMethod: all
siteSettings:
  2ef7e137-c7b8-45a2-bbaa-e33a3df84512:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
  98ec15d5-d07b-409c-9df0-23a0113620ff:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
