enableVersioning: true
handle: page
name: Page
propagationMethod: all
siteSettings:
  2ef7e137-c7b8-45a2-bbaa-e33a3df84512:
    enabledByDefault: true
    hasUrls: true
    template: /contentPage.twig
    uriFormat: '{parent.uri}/{slug}'
  98ec15d5-d07b-409c-9df0-23a0113620ff:
    enabledByDefault: true
    hasUrls: true
    template: /contentPage.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 2418a9c5-89b3-40f4-913f-0fd2af072aa1
type: structure
